### ISSUE TITLE
Determine if this repo requires Express.js and remove it if not

### ISSUE THREAD

**Issue by robbieaverill** [chec/netlify-serverless-helloworld#1]
As it may not be required.

If it's not required, remove from package.json and the places it's imported into our source files.

If it's required, close this issue.

**Comment by sloorush** [comment]
You're making requests using express so I guess it would be required

**Comment by isimplydonotexist** [comment]
It is required.

**Comment by robbieaverill** [comment]
Hey @r-ush @ya-sach1, thanks so much for your input! May I ask how you have qualified these statements?

**Comment by isimplydonotexist** [comment]
Well, the `api.js` is basically 80% Express, I don't see how it'd work without it, be it routing or even just making the web server.
Unless you plan on replacing Express.js with another library/framework I don't see why it wouldn't require it

**Comment by RajawatBanna** [comment]
@robbieaverill I am new to open source Kindly help me to get into this

**Comment by robbieaverill** [comment]
Hey @r-ush @ya-sach1 @RajawatBanna, thank you for your interest.

I've had a quick look at the repository, and ultimately while Express.js is in use here, it is not required. The purpose of this repository is to provide a barebones "hello world" example for using Netlify serverless functions and connecting them to Chec webhooks.

I've removed Express.js and all the other unused dependencies (aside from axios) in 45164ec.

Thanks for your time!
